services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unitnest_backend
    restart: unless-stopped
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    networks:
      - laravel
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: unitnest_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  db_data: