version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unitnest_backend
    restart: unless-stopped
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    networks:
      - laravel
    env_file:
      - .env # This will load variables for the Laravel app too

  db:
    image: postgres:15
    container_name: unitnest_db
    restart: unless-stopped
    env_file: # Load secrets from this file
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Now it uses the variable from the .env file
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - laravel
      
networks:
  laravel:

volumes:
  db_data: